export enum QuizEnum {
  DITADURA_MILITAR_BRASIL = 'ditadura-militar-no-brasil',
  ERA_VARGAS = 'era-vargas',
  FEUDALISMO = 'feudalismo',
  MITOLOGIA_GREGA = 'mitologia-grega',
  MITOLOGIA_NORDICA = 'mitologia-nordica',
  REVOLUCAO_FRANCESA = 'revolucao-francesa',
  REVOLUCAO_INDUSTRIAL_1 = 'revolucao-industrial-1',
  REVOLUCAO_INDUSTRIAL_2 = 'revolucao-industrial-2',
  FOLCLORE_BRASILEIRO = 'folclore-brasileiro',
  PERIODO_CRETACEO = 'periodo-cretaceo',
  PERIODO_JURASSICO = 'periodo-jurassico',
}

export const quizMap: Record<QuizEnum, { icone: string, nome: string, descricao: string, caminho: string }> = {
  // https://brasilescola.uol.com.br/o-que-e/historia/o-que-e-ditadura-militar.htm
  [QuizEnum.DITADURA_MILITAR_BRASIL]: { icone: './../../../assets/quiz/ditadura-militar.png', nome: 'Ditadura Militar no Brasil', descricao: 'No Brasil, o período mais recente de Ditadura Militar ocorreu entre os anos de 1964 e 1985. Sob o argumento de evitar uma ditadura comunista, no período da Guerra Fria, as Forças Armadas brasileiras realizaram um golpe de Estado em 31 de março de 1964, que depôs o presidente João Goulart. Eleito como vice-presidente em 1960, Jango (como era conhecido) havia assumido o poder após a renúncia de Quadros, em 1961.', caminho: QuizEnum.DITADURA_MILITAR_BRASIL },
  // https://brasilescola.uol.com.br/historiab/era-vargas.htm
  [QuizEnum.ERA_VARGAS]: { icone: './../../../assets/quiz/era-vargas.png', nome: 'Era Vargas', descricao: 'Era Vargas é o período da história do Brasil entre 1930 e 1945, quando Getúlio Vargas governou o Brasil por 15 anos e de forma contínua. Compreende o Governo Provisório, o Governo Constitucional e o Estado Novo.[1] Essa época foi um divisor de águas na história brasileira, em razão das inúmeras alterações que Vargas fez no país, tanto sociais quanto econômicas. ', caminho: QuizEnum.ERA_VARGAS },
  [QuizEnum.FEUDALISMO]: { icone: './../../../assets/quiz/feudalismo.png', nome: 'Feudalismo', descricao: 'O feudalismo foi um sistema político, econômico e social típico da Europa Ocidental durante a Idade Média, principalmente na Baixa Idade Média. Seu auge aconteceu durante os séculos XI e XIII, entrando em crise a partir de então. O feudalismo teve seu processo de formação iniciado com a desagregação do Império Romano, no século V.Esse sistema foi marcado por uma sociedade estamental que se organizava com base em três classes sociais: o clero, a nobreza e os servos. A economia girava em torno do feudo e da exploração da terra, mas um crescimento comercial significativo aconteceu a partir do século XI, permitindo o surgimento da burguesia e o crescimento urbano.', caminho: QuizEnum.FEUDALISMO },
  [QuizEnum.MITOLOGIA_GREGA]: { icone: './../../../assets/quiz/mitologia-grega.png', nome: 'Mitologia Grega', descricao: 'A Mitologia Grega reúne um conjunto de lendas e mitos que foram criados pelos gregos na antiguidade. O objetivo principal era de explicar alguns fatos, como a origem da vida, a vida após a morte, ou até mesmo os fenômenos da natureza. Assim, a criação das narrativas fantásticas que engobam a mitologia grega foi a maneira encontrada pelos gregos para preservarem sua história.', caminho: QuizEnum.MITOLOGIA_GREGA },
  [QuizEnum.MITOLOGIA_NORDICA]: { icone: '', nome: 'Mitologia Nórdica', descricao: '', caminho: 'mitologia-nordica' },
  [QuizEnum.REVOLUCAO_FRANCESA]: { icone: './../../../assets/quiz/revolucao-francesa.png', nome: 'Revolução Francesa', descricao: 'A Revolução Francesa foi um evento histórico ocorrido na França, entre 1789 e 1799, que levou ao fim do absolutismo no país, e teve importantes consequências para o mundo ocidental. Sua importância foi tamanha que os historiadores a utilizam para marcar o fim da Idade Moderna e o início da Idade Contemporânea. Com importantes transformações políticas, sociais e econômicas, a Revolução Francesa representou também a conquista do poder por parte da classe burguesa, que estava se desenvolvendo no continente europeu desde finais da Idade Média.O fato inaugural desse importante evento histórico foi a Queda da Bastilha, em 14 de julho de 1789. A Bastilha era uma prisão localizada em Paris, para aonde eram direcionados os condenados por ações políticas que desagravam à realeza absolutista francesa. Sua queda representou o enfraquecimento do poder político dos reis franceses, tornando-se um dos principais símbolos do processo revolucionário. Foi com essa revolução que a forma republicana de governo se difundiu pelo mundo, com a divisão política entre os poderes Executivo, Legislativo e Judiciário.', caminho: QuizEnum.REVOLUCAO_FRANCESA },
  [QuizEnum.REVOLUCAO_INDUSTRIAL_1]: { icone: './../../../assets/quiz/revolucao-industrial-1.png', nome: 'Primeira Revolução Industrial', descricao: 'A Primeira Revolução Industrial corresponde à primeira fase da Revolução Industrial, período caracterizado pelo grande desenvolvimento tecnológico iniciado na Europa e que, posteriormente, espalhou-se pelo mundo, provocando inúmeras e profundas transformações econômicas e sociais. A Primeira Revolução Industrial iniciou-se por volta de 1760, marcando a transição de um sistema feudal para o sistema capitalista, e durou até meados de 1850, quando, então, iniciou-se a segunda fase da Revolução Industrial', caminho: QuizEnum.REVOLUCAO_INDUSTRIAL_1 },
  [QuizEnum.REVOLUCAO_INDUSTRIAL_2]: { icone: './../../../assets/quiz/revolucao-industrial-2.png', nome: 'Segunda Revolução Industrial', descricao: 'A Segunda Revolução Industrial iniciou-se na segunda metade do século XIX, entre 1850 e 1870, e finalizou-se no fim do Segunda Guerra Mundial, entre 1939 e 1945. Essa fase da Revolução Industrial representa o início de um novo período da industrialização, vivida inicialmente na Inglaterra, mas que se expandiu para outros países.As fases da Revolução Industrial simbolizam um novo patamar alcançado no desenvolvimento da civilização humana, no que diz respeito aos avanços tecnológicos, ao surgimento de novas indústrias, bem como à capacidade produtiva de cada uma delas. Sendo assim, não se pode considerar que houve rupturas ao longo da Revolução Industrial, mas sim o alcance de novos níveis de industrialização.', caminho: QuizEnum.REVOLUCAO_INDUSTRIAL_2 },
  [QuizEnum.FOLCLORE_BRASILEIRO]: { icone: './../../../assets/quiz/folclore-brasileiro.png', nome: 'Folclore Brasileiro', descricao: '', caminho: QuizEnum.FOLCLORE_BRASILEIRO },
  [QuizEnum.PERIODO_JURASSICO]: { icone: './../../../assets/quiz/período-jurassico.png', nome: 'Período Jurássico', descricao: 'Na escala de tempo geológico, o Jurássico é o período da era Mesozoica. Cobre 65,3 milhões de anos (desde o período Triássico, de há 201,3 milhões de anos, até ao início do Cretáceo, há 145 milhões de anos). Isto é, o período Jurássico precede o Cretácico e sucede o Triássico, na era em que surgiu o Oceano Atlântico.', caminho: QuizEnum.PERIODO_JURASSICO },
  [QuizEnum.PERIODO_CRETACEO]: { icone: '', nome: 'Período Cretáceo', descricao: '', caminho: 'periodo-cretaceo' },
};
